#!/usr/bin/env python3
import argparse
import json
import subprocess
import sys
from pathlib import Path


def clone_repo(git_url: str, branch: str, target_dir: Path, repo_name: str):
    """Clone a git repository to the target directory."""
    repo_path = target_dir / repo_name

    if repo_path.exists():
        print(f"Skipping {repo_name} (already exists)")
        return True

    try:
        print(f"Cloning {repo_name} from {git_url} (branch: {branch})...")
        subprocess.run(
            [
                "git",
                "clone",
                "--depth",
                "1",
                "--branch",
                branch,
                git_url,
                str(repo_path),
            ],
            check=True,
            capture_output=True,
            text=True,
        )
        print(f"✓ Successfully cloned {repo_name}")
        return True
    except subprocess.CalledProcessError as e:
        print(f"✗ Failed to clone {repo_name}: {e.stderr}", file=sys.stderr)
        return False


def main():
    parser = argparse.ArgumentParser(
        description="Clone ROS2 repositories from a JSON file generated by query_repos.py"
    )
    parser.add_argument(
        "--json-file",
        required=True,
        help="Path to the JSON file containing repository information",
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Directory where repositories will be cloned",
    )
    parser.add_argument(
        "--no-deps",
        action="store_true",
        help="Only clone packages without dependencies (for dev purposes)",
    )
    args = parser.parse_args()

    json_file = Path(args.json_file)
    output_dir = Path(args.output_dir)

    if not json_file.exists():
        print(f"Error: JSON file {json_file} does not exist", file=sys.stderr)
        sys.exit(1)

    # Create output directory
    output_dir.mkdir(parents=True, exist_ok=True)

    # Load repository data
    with open(json_file, "r") as f:
        data = json.load(f)

    repositories = data.get("repositories", [])
    if not repositories:
        print("No repositories found in JSON file", file=sys.stderr)
        sys.exit(1)

    # Filter packages without dependencies if --no-deps is specified
    if args.no_deps:
        repositories = [
            repo for repo in repositories
            if not repo.get("dependencies") or len(repo.get("dependencies", [])) == 0
        ]
        print(f"Filtering to packages without dependencies...")

    print(f"Found {len(repositories)} repositories to clone")
    print(f"Target directory: {output_dir.absolute()}\n")

    # Clone each repository
    success_count = 0
    fail_count = 0

    for repo in repositories:
        name = repo.get("name")
        git_url = repo.get("git_url")
        branch = repo.get("branch")

        if not all([name, git_url, branch]):
            print(f"Skipping invalid entry: {repo}", file=sys.stderr)
            fail_count += 1
            continue

        if clone_repo(git_url, branch, output_dir, name):
            success_count += 1
        else:
            fail_count += 1

    # Summary
    print(f"\n{'=' * 60}")
    print(f"Cloning completed:")
    print(f"  ✓ Success: {success_count}")
    print(f"  ✗ Failed:  {fail_count}")
    print(f"  Total:     {len(repositories)}")
    print(f"{'=' * 60}")


if __name__ == "__main__":
    main()
